### ISSUE TITLE
socklen_t is not always u32

### ISSUE THREAD

**Issue by powturns** [rust-vsock/tokio-vsock#28]
`VsockStream.connect` calls:

```rust
            connect(
                socket,
                &vsock_addr as *const _ as *const sockaddr,
                size_of::<sockaddr_vm>() as u32,
            )
```

However, the `len` argument of `connect` isn't guaranteed to always be `u32` (for example, some android platforms use `i32`). 

Instead, it is likely more robust to cast `size_of::<sockaddr_vm>()` to `socklen_t`. Eg: 
```rust
            connect(
                socket,
                &vsock_addr as *const _ as *const sockaddr,
                size_of::<sockaddr_vm>() as socklen_t,
            )
```

**Comment by Tim-Zhang** [comment]
Good catch @powturns , would you mind filing a pull request for this?
