### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jalil-salame** [rust-vsock/tokio-vsock#42]
We should probably have a new release soon; `vsock-rs` has a new version and a few changes have been made here. I don't know how to go about it though. How does one prepare a new release of this library?

> Oh and looks like it's been a year since the last release and there has been a few changes since. Could please have one soon? :pray:

_Originally posted by @zeenix in https://github.com/rust-vsock/tokio-vsock/issues/41#issuecomment-1892678025_

**Comment by qwandor** [comment]
It looks like only @dpeckett, @Tim-Zhang and @fsyncdadmin have permission to push releases to crates.io.

**Comment by jalil-salame** [comment]
It's probably best for someone to prepare a pull request bumping the dependencies and our version number. I could do it in two weeks if no-one is available.

**Comment by dpeckett** [comment]
@qwandor you should now have admin on crates.io for both vsock packages.

**Comment by qwandor** [comment]
`tokio-vsock` 0.5.0 is now published to crates.io.
